version: "3.9"

services:
    truehome_nginx:
        container_name: truehome_nginx
        image: nginx:alpine
        ports:
            - 8001:80
        volumes:
            - ./docker/webapp_nginx/sites:/etc/nginx/conf.d
            - ./webapp/build:/var/www/app
        networks: 
            - truehomeNet
        environment:
            - VIRTUAL_HOST=truehome.edcilo.com
            - LETSENCRYPT_HOST=truehome.edcilo.com
            - LETSENCRYPT_EMAIL=me@edcilo.com
networks:
    truehomeNet:
        driver: "bridge"
