version: "3.9"

services:
    dogger_ui_nginx:
        container_name: dogger_ui_nginx
        image: nginx:alpine
        volumes:
            - ./docker/webapp_nginx/sites:/etc/nginx/conf.d
            - ./webapp/build:/var/www/app
        environment:
            - VIRTUAL_HOST=doggerui.edcilo.com
            - LETSENCRYPT_HOST=doggerui.edcilo.com
            - LETSENCRYPT_EMAIL=me@edcilo.com

networks:
    default:
        external:
            name: edcNet
