# Generated by Django 3.2.3 on 2021-05-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.CharField(choices=[('call', 'Llamada al cliente'), ('meeting', 'Visita a propiedad presencial'), ('virtual', 'Visita virtual a propiedad')], max_length=50),
        ),
    ]
