# Generated by Django 3.2.3 on 2021-05-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_auto_20210517_2218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='customer',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='date',
            new_name='schedule_at',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('call', 'Llamada al cliente'), ('virtual', 'Visita virtual a propiedad'), ('meeting', 'Visita a propiedad presencial')], default='sell', max_length=50),
            preserve_default=False,
        ),
    ]
