# Generated by Django 3.2.3 on 2021-05-18 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_auto_20210517_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='seller',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sellers.seller'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('virtual', 'Visita virtual a propiedad'), ('call', 'Llamada al cliente'), ('meeting', 'Visita a propiedad presencial')], max_length=50),
        ),
    ]
