# Generated by Django 3.2.3 on 2021-05-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_auto_20210518_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='finished_at',
            field=models.DateTimeField(default='2021-05-18 00:00:00'),
            preserve_default=False,
        ),
    ]
