# Generated by Django 3.2.3 on 2021-05-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_activity_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('meeting', 'Visita a propiedad presencial'), ('virtual', 'Visita virtual a propiedad'), ('call', 'Llamada al cliente')], max_length=50),
        ),
    ]
