export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT"

export const WALKERS_SET = "WALKERS_SET"

export const RESERVATIONS_SET = "RESERVATIONS_SET";
export const RESERVATION_CREATE = "RESERVATION_CREATE";
export const RESERVATION_UPDATE = "RESERVATION_UPDATE";
export const RESERVATION_DELETE = "RESERVATION_DELETE";
